apiVersion: v1
kind: Service
metadata:
  name: kubearmor
  labels:
    {{- include "kubearmor-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubearmor-helm.selectorLabels" . | nindent 4 }}
    container: kubearmor