replicaCount: 1
kubearmor:
  image:
    repository: gcr.io/accuknox/snapshot/kubearmor
    #repository: accuknox/kubearmor
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  name: kubearmor
  serviceAccountName: kubearmor
  volumes:
    - name: docker-sock-path # docker
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: usr-src-path # BPF
      hostPath:
        path: /usr/src
        type: Directory
    - name: lib-modules-path # BPF
      hostPath:
        path: /lib/modules
        type: Directory
    - name: sys-fs-bpf-path # BPF
      hostPath:
        path: /sys/fs/bpf
        type: Directory
    - name: sys-kernel-debug-path # BPF
      hostPath:
        path: /sys/kernel/debug
        type: Directory
    - name: etc-apparmor-d-path # AppArmor
      hostPath:
        path: /etc/apparmor.d
        type: Directory
    - name: var-log-audit-path # GKE-Auditd
      hostPath:
        path: /var/log/audit
        type: Directory
    - name: os-release-path # OS
      hostPath:
        path: /etc/os-release
        type: File
  volumeMounts:
    - name: docker-sock-path # docker (read-only)
      mountPath: /var/run/docker.sock
      readOnly: true
    - name: usr-src-path # BPF (read-only)
      mountPath: /usr/src
      readOnly: true
    - name: lib-modules-path # BPF (read-only)
      mountPath: /lib/modules
      readOnly: true
    - name: sys-fs-bpf-path # BPF (read-write)
      mountPath: /sys/fs/bpf
    - name: sys-kernel-debug-path # BPF (read-write)
      mountPath: /sys/kernel/debug
    - name: etc-apparmor-d-path # AppArmor (read-write)
      mountPath: /etc/apparmor.d
    - name: var-log-audit-path # GKE-Auditd (read-only)
      mountPath: /var/log/audit
      readOnly: true
    - name: os-release-path # OS (read-only)
      mountPath: /media/root/etc/os-release
      readOnly: true

  livenessProbe:
    exec:
      command:
      - /bin/bash
      - -c
      - |
        if [ -z $(pgrep kubearmor) ]; then
          exit 1;
        fi;
    initialDelaySeconds: 30
    periodSeconds: 10


cosauditd:
  image:
    repository: gcr.io/accuknox/snapshot/kubearmor-cos-auditd
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  name: kubearmor
  serviceAccountName: kubearmor
  env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
  volumes:
    - name: host-path
      hostPath:
        path: /
        type: Directory
    - name: lib-systemd-path
      hostPath:
        path: /usr/lib64
        type: Directory
    - name: var-log-path
      hostPath:
        path: /var/log
        type: Directory
  volumeMounts:
    - name: lib-systemd-path
      mountPath: /host/lib
      readOnly: true
    - name: var-log-path
      mountPath: /var/log

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment:
  name: kubearmor-deployment
label:
  name: kubearmor

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths:
#      - path: /
#        backend:
#          serviceName: chart-example.local
#          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicaCount: 2
  maxReplicaCount: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

nodeSelector: {}

tolerations: []

affinity: {}